title: type-race
description: Project page for type-race game
author: "Jacob Likins and Jacob Keller"

theme: minima

base_url: /home

# Minima: custom header links
header_pages:
  - setup.md
  - about.md
  - resources.md
